O와 X로 채워진 표가 있습니다. 표 1칸은 1 x 1 의 정사각형으로 이루어져 있습니다. 표에서 O로 이루어진 가장 큰 정사각형을 찾아 넓이를 반환하는 findLargestSquare 함수를 완성하세요.

예를 들어
1	2	3	4	5<br/>
X	O	O	O	X<br/>
X	O	O	O	O<br/>
X	X	O	O	O<br/>
X	X	O	O	O<br/>
X	X	X	X	X<br/>

가 있다면 정답은
1	2	3	4	5<br/>
X	O	O	O	X<br/>
X	O	**V	V	V**<br/>
X	X	**V	V	V**<br/>
X	X	**V	V	V**<br/>
X	X	X	X	X<br/>

가 되며 넓이는 9가 되므로 9를 반환해 주면 됩니다.

In [184]:
import numpy as np

def findLargestSquare(board):
    print('***********************')
    print('findLargestSquare start')
    intBoard = np.zeros((len(board),len(board[0])))
    

    for x in range(len(board)):
        for y in range(len(board[0])):
            if board[x][y] == 'O':
                intBoard[x][y] = 1

            elif board[x][y] == 'X':
                intBoard[x][y] = 0
    print(intBoard)

    bd_len_x = len(intBoard)
    bd_len_y = len(intBoard[0])
    len_min = min(bd_len_x,bd_len_y)
    for mask in range(len_min,0,-1):
        print(mask)

        for x in range(bd_len_x-mask+1):
            for y in range(bd_len_y-mask+1):
                ss = sum(sum(intBoard[x:x+mask, y:y+mask]))
                print(ss, mask*mask)
                print(intBoard[x:x+mask, y:y+mask])
                if ss == mask*mask:
                    return ss

                


In [185]:
testBoard = [['X','O','O','O','X','X','O','O','O','X'],
             ['X','O','O','O','O','X','O','O','O','X'],
             ['X','X','O','O','O','X','O','O','O','X'],
             ['X','X','O','O','O','X','O','O','O','X'],
             ['X','X','X','X','X','X','O','O','O','O'],
             ['X','O','O','O','O','X','O','O','O','O'],
             ['X','X','O','O','O','X','O','O','O','O'],
             ['X','X','O','O','O','X','O','O','O','O']]

testBoard2 = [['X','O','O','O','X'],
              ['X','O','O','O','O'],
              ['X','X','O','O','O'],
              ['X','X','X','O','O'],
              ['X','X','X','X','X']]

print(findLargestSquare(testBoard))
print(len(testBoard),len(testBoard[0]))

***********************
findLargestSquare start
[[0. 1. 1. 1. 0. 0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
 [0. 0. 1. 1. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1. 1. 1.]]
8
39.0 64
[[0. 1. 1. 1. 0. 0. 1. 1.]
 [0. 1. 1. 1. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 1. 1. 1. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1.]
 [0. 0. 1. 1. 1. 0. 1. 1.]]
47.0 64
[[1. 1. 1. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 1.]
 [0. 1. 1. 1. 0. 1. 1. 1.]]
48.0 64
[[1. 1. 0. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 1. 1. 0.]
 [1. 1. 1. 0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]
 [1. 1. 1. 0. 1. 1. 1. 1.]]
7
27.0 49


In [99]:
import numpy as np

intBoard = np.zeros((len(testBoard),len(testBoard)))
print(intBoard)

for x in range(len(testBoard)):
    for y in range(len(testBoard)):
        if testBoard[x][y] == 'O':
            intBoard[x][y] = 1
            
        elif testBoard[x][y] == 'X':
            intBoard[x][y] = 0
            
print(intBoard)            
y = sum(sum(intBoard[2:,2:]))

bd_len = len(intBoard)
for mask in range(bd_len,0,-1):
    print(mask)
    
    for x in range(bd_len-mask+1):
        for y in range(bd_len-mask+1):
            ss = sum(sum(intBoard[x:x+mask, y:y+mask]))
            if ss == mask*mask:
                return ss
                
            print(intBoard[x:x+mask, y:y+mask])
        
    

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
5
[[0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0.]]
4
[[0. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]]
[[1. 1. 1. 0.]
 [1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 1. 1. 1.]]
[[0. 1. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 0. 0.]]
3
[[0. 1. 1.]
 [0. 1. 1.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 1. 1.]]
[[1. 1. 0.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 1. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]
[[1. 1. 1.]
 [0. 1. 1.]
 [0. 1. 1.]]
9.0
[[0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 1. 1.]
 [0. 1. 1.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [0. 0. 0.]]
2
[[0. 1.]
 [0. 1.]]
4.0
[[0. 1.]
 [0. 0.]]
[[1. 1.]
 [0. 1.]]
4.0
[[0. 0.]
 [0. 0.]]
[[0. 1.]
 [0. 1.]]
4.0
[[0. 0.]
 [0. 0.]]
[[0. 1.]
 [0. 0.]]
[[1. 1.]
 [0. 0.]]
[[1. 1.]
 [

#  map(sum, input)
Basically, map(sum, input) will return a list with the sums across all your rows, <br/>then, the outer most sum will add up that list.

In [33]:
def func(x):
    return x * 2  

# map함수를 적용하면 map object형태임
# list로 변환하여 print해야 보임
print((map(func, [1, 2, 3, 4])))
print(list(map(func, [1, 2, 3, 4])))

[2, 4, 6, 8]


In [145]:
intBoard = [ [0 for _ in range(len(testBoard))] for _ in range(len(testBoard))]
intBoard
for x in range(len(testBoard)):
    for y in range(len(testBoard)):
        if testBoard[x][y] == 'O':
            intBoard[x][y] = 1
            
        elif testBoard[x][y] == 'X':
            intBoard[x][y] = 0
print(intBoard)
print(max(max(intBoard)))
len(intBoard)

[[0, 1, 1, 1, 0, 0, 1, 1], [0, 1, 1, 1, 1, 0, 1, 1], [0, 0, 1, 1, 1, 0, 1, 1], [0, 0, 1, 1, 1, 0, 1, 1], [0, 0, 0, 0, 0, 0, 1, 1], [0, 1, 1, 1, 1, 0, 1, 1], [0, 0, 1, 1, 1, 0, 1, 1], [0, 0, 1, 1, 1, 0, 1, 1]]
1


8

In [43]:
sum(map(sum, intBoard[1:3][:]))

7

# Dynamic Programming

![](./img/DP.png)

In [146]:
def findLargestSquare1(board):
    # 'O'에 해당하는 것을 1로, 'X'에 해당하는 값을 0으로 바꿔준다.
    table = [[1 if x == "O" else 0 for x in sub_board] for sub_board in board]
    max_square = 0
    for x in range(1, len(table)):
        for y in range(1, len(table[x])):
            # 만약 table[x][y]의 값이 0(즉, 'X')라면 정사각형을 만들 수 없으므로 건너 뛴다.
            if table[x][y] == 0:
                continue
            # 해당 좌표 기준(x,y) : 왼쪽검사(x, y-1), 위쪽 검사(x-1, y), 11시 방향 대각선 검사(x-1, y-1)
            else:
                # 최소값을 하나 뽑아낸다. 차례대로 min(왼쪽 좌표, 위쪽 좌표, 왼쪽 대각선 좌표)를 의미한다.
                _min = min([table[x][y-1], table[x-1][y], table[x-1][y-1]])
                table[x][y] = _min + 1

                # 만약, max_square보다 큰 값이 등장하면, 교체해준다.
                if max_square < table[x][y]:
                    max_square = table[x][y]

    # 넓이를 반환해야 하므로 제곱을 해서 반환한다.
    return max_square**2