영희는 땅따먹기 게임에 푹 빠졌습니다. <br/>
땅따먹기 게임의 땅은 총 N행 4열로 나누어져 있고, 모든 칸에는 점수가 쓰여 있습니다.<br/>
땅을 밟으면서 한 행씩 내려올 때, 영희는 각 행의 4칸 중 1칸만 밟으면서 내려올 수 있습니다.<br/>
땅따먹기 게임에는 같은 열을 연속해서 밟을 수가 없는 특수 규칙이 있습니다. <br/>
즉, 1행에서 (5)를 밟았다면,
<br/>2행의 (8)은 밟을 수가 없게 됩니다. 
마지막 행까지 모두 내려왔을 때, 점수가 가장 높은 사람이 게임의 승자가 됩니다. <br/>

여러분이 hopscotch 함수를 제작하여 영희가 최대 몇 점을 얻을 수 있는지 알려주세요. <br/>
예를 들어<br/>
1 2 3 5<br/>
5 6 7 8<br/>
4 3 2 1<br/>
의 땅이 있다면, 영희는 각 줄에서 (5), (7), (4) 땅을 밟아 16점을 최고점으로 받을 수 있으며, hopscotch 함수에서는 16을 반환해주면 됩니다.

In [34]:
(m,i) = max((v,i) for i,v in enumerate(b[0]))
print (m,i) #(5, 2)

5 3


In [153]:
b =  [[ 1, 2, 3, 5 ], [ 5, 6, 7, 8 ], [4, 3, 2000, 1]]


score = np.zeros(len(b[0]))
for x in range(len(b[0])):
    print('*************')
    
    tmp_borad = np.array(b)
    print(tmp_borad)
    max_val, max_idx = max((m,i) for i,m in enumerate(b[0]))
    sum_mv=max_val
    b[0][max_idx]=0
    tmp_borad[1][max_idx]=0
    #print(np.array(b))
    print(max_val, max_idx, sum_mv)
    for y in range(1, len(b)):
        sort_tb = np.sort(tmp_borad[y-1])
        if sort_tb[-1] == sort_tb[-2]:
            print('pass')
            
        else:
            tmp_borad[y][max_idx]=0
            
        max_val, max_idx = max((m,i) for i,m in enumerate(tmp_borad[y]))
        sum_mv += max_val
        print(max_val, max_idx, sum_mv)
    
    score[x]=sum_mv
    print(score)
        
            

*************
[[   1    2    3    5]
 [   5    6    7    8]
 [   4    3 2000    1]]
5 3 5
7 2 12
4 0 16
[16.  0.  0.  0.]
*************
[[   1    2    3    0]
 [   5    6    7    8]
 [   4    3 2000    1]]
3 2 3
8 3 11
2000 2 2011
[  16. 2011.    0.    0.]
*************
[[   1    2    0    0]
 [   5    6    7    8]
 [   4    3 2000    1]]
2 1 2
8 3 10
2000 2 2010
[  16. 2011. 2010.    0.]
*************
[[   1    0    0    0]
 [   5    6    7    8]
 [   4    3 2000    1]]
1 0 1
8 3 9
2000 2 2009
[  16. 2011. 2010. 2009.]


위의 방법은 <br/>
 [[ 1, 2, 3, 5 ], <br/>
 [ 5, 6, 7, 8 ],<br/>
 [4, 3, 2000, 1]]<br/>
 일때 알맞은 값 반환하지 못함
 

In [152]:
def hopscotch(board, size):
    sumList = [0]*4
    print(sumList)
    for row in board:
        tmp = sumList.copy()
        for i in range(len(row)):
            sumList[i] = row[i] + max(tmp[:i] + tmp[i+1:])
        print(sumList)
    return max(sumList)



#아래는 테스트로 출력해 보기 위한 코드입니다.
board =  [[ 1, 2, 3, 5 ], [ 5, 6, 7, 8 ], [4, 3, 2000, 1]]
print(hopscotch(board, 3))


[0, 0, 0, 0]
[1, 2, 3, 5]
[10, 11, 12, 11]
[16, 15, 2011, 13]
2011


In [ ]:
def hopscotch(board, size):
    answer = [0]*4
    for i in range(size) :
        row = board[i][:]
        mx = answer[:]
        for j in range(4) :
            mx2 = mx[:]
            mx2.pop(j)
            answer[j] = row[j] + max(mx2)
    return max(answer)

#아래는 테스트로 출력해 보기 위한 코드입니다.
board =  [[ 1, 2, 3, 5 ], [ 5, 6, 7, 8 ], [4, 3, 2, 1]]
print(hopscotch(board, 3))


In [ ]:
def hopscotch(board, size):
    result = 0
    # 땅따먹기 게임으로 얻을 수 있는 최대 점수는?
    for i in range(1,size):
        for j in range(4):
            t=board[i-1][0:j]+board[i-1][j+1:]
            board[i][j]+=max(t)
    return max(board[size-1])


#아래는 테스트로 출력해 보기 위한 코드입니다.
board =  [[ 1, 2, 3, 5 ], [ 5, 6, 7, 8 ], [4, 3, 2, 1]]
print(hopscotch(board, 3))